# Markdownlint configuration for mkdocs-material

# Disable line length - mkdocs content often has long lines
MD013: false

# Allow inline HTML (needed for some mkdocs features)
MD033: false

# Allow bare URLs (common in annotations)
MD034: false

# Code block style - conflicts with admonitions
MD046: false

# Allow emphasis as headers (used in some mkdocs patterns)
MD036: false

# First line doesn't need to be a top-level heading
MD041: false

# Allow duplicate headings (e.g., "Why this matters for virtualization" in multiple sections)
MD024: false

# Allow code blocks without language (sometimes intentional for plain output)
MD040: false
